[package]
name = "glfw3-sys"
version = "0.1.0+3.4"
edition = "2021"
build = "build.rs"

[dependencies]

[build-dependencies]
cmake = "0.1"

[dev-dependencies]
parking_lot = "0.12"

[features]
default = ["vendored"]
wayland = []
vendored = []
